versions: "3"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db # Create a volume for the DB.
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    restart: always
    env_file:
      - client.dev.env
    stdin_open: true # Hot reloading create react app: https://github.com/facebook/create-react-app/issues/8688#issuecomment-602110747
    volumes:
      - ./client:/app #Synchronise docker container with local change
      - /app/node_modules #Avoid re-copying local node_modules. Cache in volume.
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    env_file:
      - server.dev.env
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - ./server:/app #Synchronise docker container with local change
      - /app/node_modules #Avoid re-copying local node_modules. Cache in volume.

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:3000"
      - "8082:8081"
    volumes:
      - ./client/nginx/nginx.conf:/etc/nginx/nginx.conf # Nginx config
      - /etc/nginx/certs:/etc/nginx/certs # SSL certificates
    depends_on:
      - client
      - server
    restart: always
